export const COLORS = {
  heart: "#e05252",
  diabetes: "#f59e0b",
  kidney: "#8b5cf6",
  liver: "#10b981",
  stroke: "#3b82f6",
  hypertension: "#ec4899",
};

export const DISEASE_CONFIG: Record<string, any> = {
  heart: {
    label: "Heart Disease",
    icon: "❤️",
    color: "#e05252",
    features: ["age", "chestPain", "restingBP", "cholesterol", "fastingBS", "maxHR", "exerciseAngina", "smoking"],
    thresholds: { low: 30, medium: 60 },
  },
  diabetes: {
    label: "Diabetes",
    icon: "🩸",
    color: "#f59e0b",
    features: ["age", "bmi", "glucose", "insulin", "bloodPressure", "pregnancies", "skinThickness", "dpf"],
    thresholds: { low: 25, medium: 55 },
  },
  kidney: {
    label: "Kidney Disease",
    icon: "🫘",
    color: "#8b5cf6",
    features: ["age", "bloodPressure", "albumin", "bloodGlucose", "bloodUrea", "serumCreatinine", "sodium", "hemoglobin"],
    thresholds: { low: 20, medium: 50 },
  },
  liver: {
    label: "Liver Disease",
    icon: "🟤",
    color: "#10b981",
    features: ["age", "totalBilirubin", "alkalinePhosphotase", "alanineAminotransferase", "aspartateAminotransferase", "totalProteins", "albumin", "gender"],
    thresholds: { low: 25, medium: 55 },
  },
  stroke: {
    label: "Stroke",
    icon: "🧠",
    color: "#3b82f6",
    features: ["age", "hypertension", "heartDisease", "avgGlucose", "bmi", "smokingStatus", "workType", "everMarried"],
    thresholds: { low: 20, medium: 45 },
  },
  hypertension: {
    label: "Hypertension",
    icon: "📊",
    color: "#ec4899",
    features: ["age", "bmi", "saltIntake", "physicalActivity", "alcoholUse", "smokingStatus", "familyHistory", "stressLevel"],
    thresholds: { low: 30, medium: 60 },
  },
};

export const FIELD_CONFIG: Record<string, any> = {
  age: { label: "Age", type: "number", min: 1, max: 120, unit: "yrs", placeholder: "45" },
  chestPain: { label: "Chest Pain Type", type: "select", options: ["None", "Typical Angina", "Atypical Angina", "Non-anginal", "Asymptomatic"] },
  restingBP: { label: "Resting Blood Pressure", type: "number", min: 60, max: 200, unit: "mmHg", placeholder: "120" },
  cholesterol: { label: "Cholesterol", type: "number", min: 100, max: 600, unit: "mg/dL", placeholder: "200" },
  fastingBS: { label: "Fasting Blood Sugar", type: "select", options: ["< 120 mg/dL", "> 120 mg/dL"] },
  maxHR: { label: "Max Heart Rate", type: "number", min: 60, max: 220, unit: "bpm", placeholder: "150" },
  exerciseAngina: { label: "Exercise Angina", type: "select", options: ["No", "Yes"] },
  smoking: { label: "Smoking Status", type: "select", options: ["Never", "Former", "Current"] },
  bmi: { label: "BMI", type: "number", min: 10, max: 60, unit: "kg/m²", placeholder: "25.0", step: "0.1" },
  glucose: { label: "Glucose Level", type: "number", min: 40, max: 500, unit: "mg/dL", placeholder: "100" },
  insulin: { label: "Insulin", type: "number", min: 0, max: 900, unit: "μU/mL", placeholder: "80" },
  bloodPressure: { label: "Blood Pressure", type: "number", min: 40, max: 130, unit: "mmHg", placeholder: "70" },
  pregnancies: { label: "Pregnancies", type: "number", min: 0, max: 20, placeholder: "0" },
  skinThickness: { label: "Skin Thickness", type: "number", min: 0, max: 100, unit: "mm", placeholder: "20" },
  dpf: { label: "Diabetes Pedigree Function", type: "number", min: 0, max: 3, unit: "", placeholder: "0.5", step: "0.01" },
  albumin: { label: "Albumin", type: "number", min: 1, max: 5, placeholder: "3" },
  bloodGlucose: { label: "Blood Glucose Random", type: "number", min: 60, max: 500, unit: "mg/dL", placeholder: "120" },
  bloodUrea: { label: "Blood Urea", type: "number", min: 5, max: 300, unit: "mg/dL", placeholder: "25" },
  serumCreatinine: { label: "Serum Creatinine", type: "number", min: 0.1, max: 20, unit: "mg/dL", placeholder: "1.0", step: "0.1" },
  sodium: { label: "Sodium", type: "number", min: 100, max: 160, unit: "mEq/L", placeholder: "138" },
  hemoglobin: { label: "Hemoglobin", type: "number", min: 3, max: 20, unit: "g/dL", placeholder: "14" },
  totalBilirubin: { label: "Total Bilirubin", type: "number", min: 0, max: 30, unit: "mg/dL", placeholder: "1.0", step: "0.1" },
  alkalinePhosphotase: { label: "Alkaline Phosphatase", type: "number", min: 20, max: 2000, unit: "IU/L", placeholder: "100" },
  alanineAminotransferase: { label: "SGPT (ALT)", type: "number", min: 5, max: 2000, unit: "IU/L", placeholder: "30" },
  aspartateAminotransferase: { label: "SGOT (AST)", type: "number", min: 5, max: 3000, unit: "IU/L", placeholder: "30" },
  totalProteins: { label: "Total Proteins", type: "number", min: 2, max: 10, unit: "g/dL", placeholder: "6.5", step: "0.1" },
  gender: { label: "Gender", type: "select", options: ["Male", "Female"] },
  hypertension: { label: "Hypertension", type: "select", options: ["No", "Yes"] },
  heartDisease: { label: "Heart Disease", type: "select", options: ["No", "Yes"] },
  avgGlucose: { label: "Avg Glucose Level", type: "number", min: 40, max: 300, unit: "mg/dL", placeholder: "100", step: "0.1" },
  smokingStatus: { label: "Smoking Status", type: "select", options: ["Never smoked", "Formerly smoked", "Smokes", "Unknown"] },
  workType: { label: "Work Type", type: "select", options: ["Private", "Self-employed", "Govt_job", "Children", "Never_worked"] },
  everMarried: { label: "Ever Married", type: "select", options: ["No", "Yes"] },
  saltIntake: { label: "Salt Intake", type: "select", options: ["Low", "Moderate", "High"] },
  physicalActivity: { label: "Physical Activity", type: "select", options: ["Sedentary", "Light", "Moderate", "Active"] },
  alcoholUse: { label: "Alcohol Use", type: "select", options: ["None", "Occasional", "Regular", "Heavy"] },
  familyHistory: { label: "Family History of HTN", type: "select", options: ["No", "Yes"] },
  stressLevel: { label: "Stress Level", type: "select", options: ["Low", "Moderate", "High", "Very High"] },
};

export const CHAT_RESPONSES: Record<string, string> = {
  heart: "Based on your cardiovascular profile, I recommend: (1) Maintain LDL cholesterol below 100 mg/dL, (2) Exercise 150+ minutes weekly, (3) Follow the DASH diet, (4) Monitor blood pressure daily, (5) Avoid smoking and limit alcohol.",
  diabetes: "To manage your diabetes risk: (1) Maintain a healthy BMI (18.5–24.9), (2) Limit refined carbohydrates and sugars, (3) Exercise regularly to improve insulin sensitivity, (4) Monitor fasting blood glucose, (5) Consider a fiber-rich Mediterranean diet.",
  kidney: "For kidney health: (1) Stay well-hydrated (2–3L water daily), (2) Control blood pressure and blood sugar, (3) Reduce sodium intake below 2,300mg/day, (4) Avoid nephrotoxic medications like NSAIDs, (5) Get regular kidney function tests.",
  liver: "Liver health tips: (1) Avoid alcohol or limit to 1 drink/day, (2) Maintain a healthy weight to prevent fatty liver, (3) Vaccinate against hepatitis A & B, (4) Avoid herbal supplements that can cause liver toxicity, (5) Exercise regularly.",
  stroke: "Stroke prevention: (1) Control blood pressure (target <130/80), (2) Manage atrial fibrillation if present, (3) Quit smoking immediately, (4) Control blood sugar levels, (5) Take prescribed antiplatelet or anticoagulant therapy.",
  hypertension: "Blood pressure management: (1) Reduce sodium to <1,500mg/day, (2) Follow DASH diet with more potassium, (3) Exercise 30 minutes daily, (4) Limit alcohol to 1–2 drinks/day, (5) Manage stress with meditation or yoga.",
};
